### ISSUE TITLE
500 error on contract logs

### ISSUE THREAD

**Issue by FerumFlex** [aeternity/ae_mdw#1035]
You can check this error is live
https://testnet.aeternity.io/mdw/v2/contracts/logs?direction=backward&contract_id=ct_9rPBQUmEsCoBWpSSU2dWB2qAYA9u71AcjY5vDoziS14LTtd7Z
just copy response incase it will be fixed

```
# Jason.EncodeError at GET /v2/contracts/logs

Exception:

    ** (Jason.EncodeError) invalid byte 0xEA in <<28, 234, 57, 90, 91, 243, 243, 125, 219, 245, 226, 227, 63, 160, 30, 254, 146, 138, 184, 9, 88, 13, 178, 123, 176, 162, 255, 227, 149, 61, 28, 151, 228, 79, 157, 45, 21, 247, 253, 77, 112, 101, 135, 49, 175, 202, 102, 147, 92, 35, ...>>
        (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.6.12) lib/phoenix/controller.ex:281: Phoenix.Controller.json/2
        (ae_mdw 1.29.1) lib/ae_mdw_web/controllers/contract_controller.ex:1: AeMdwWeb.ContractController.action/2
        (ae_mdw 1.29.1) lib/ae_mdw_web/controllers/contract_controller.ex:1: AeMdwWeb.ContractController.phoenix_controller_pipeline/2
        (phoenix 1.6.12) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (ae_mdw 1.29.1) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.plug_builder_call/2
        (ae_mdw 1.29.1) lib/plug/debugger.ex:136: AeMdwWeb.Endpoint."call (overridable 3)"/2
        (ae_mdw 1.29.1) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.call/2
        (phoenix 1.6.12) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /home/aeternity/node/ae_mdw/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
    

## Connection details

### Params

    %{"contract_id" => "ct_9rPBQUmEsCoBWpSSU2dWB2qAYA9u71AcjY5vDoziS14LTtd7Z", "direction" => "backward"}

### Request info

  * URI: http://mdw.testnet.aeternity.io:80/v2/contracts/logs
  * Query string: direction=backward&contract_id=ct_9rPBQUmEsCoBWpSSU2dWB2qAYA9u71AcjY5vDoziS14LTtd7Z

### Headers
  
  * accept-encoding: gzip
  * host: mdw.testnet.aeternity.io
  * sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
  * sec-ch-ua-mobile: ?0
  * sec-ch-ua-platform: "macOS"
  * sec-fetch-dest: document
  * sec-fetch-mode: navigate
  * sec-fetch-site: none
  * sec-fetch-user: ?1
  * upgrade-insecure-requests: 1
  * user-agent: Amazon CloudFront
  * via: 2.0 297a2b3ab6b9933e5d097fc4266514ae.cloudfront.net (CloudFront)
  * x-amz-cf-id: JSpCsxPlZbXK1y5DQWhxInm5n4CAINbzgaQwugb2r70O2tPiWigcmg==
  * x-forwarded-for: 91.243.31.7, 64.252.86.224, 172.31.5.81
  * x-forwarded-proto: http
  * x-real-ip: 91.243.31.7

### Session

    %{}
```

Steps to reproduce:
1. hard to say, it seems it appears when I emit event `SwapSigned(hash, bytes(65))` from contract.

**Comment by thepiwo** [comment]
Thanks for your feedback, this issue is still present in the current master branch, I'll coordinate with the team to get this fixed asap.

**Comment by thepiwo** [comment]
@FerumFlex the fix as proposed will encode `bytes` as base64

**Comment by FerumFlex** [comment]
probably it is a good one)

**Comment by thepiwo** [comment]
@FerumFlex I will ping here when it's been deployed to production

**Comment by thepiwo** [comment]
the fix is now deployed to production
