### ISSUE TITLE
Chain listener crash during block changes

### ISSUE THREAD

**Issue by dincho** [aeternity/ae_mdw#1664]
```
2024-01-10 10:26:55.226 [error] GenServer AeMdwWeb.Websocket.ChainListener terminating
** (ArgumentError) argument error
    (stdlib 3.14.2.2) :ets.member(:broadcast_hashes, {:key, :v1, <<204, 91, 76, 107, 137, 20, 168, 191, 240, 182, 78, 225, 145, 20, 11, 255, 232, 219, 67, 224, 109, 157, 233, 71, 167, 222, 192, 106, 170, 27, 62, 32>>, :node})
    (ae_mdw 1.68.0) lib/ae_mdw/ets_cache.ex:49: AeMdw.EtsCache.member/2
    (ae_mdw 1.68.0) lib/ae_mdw_web/websocket/broadcaster.ex:39: AeMdwWeb.Websocket.Broadcaster.broadcast_key_block/5
    (ae_mdw 1.68.0) lib/ae_mdw_web/websocket/chain_listener.ex:40: AeMdwWeb.Websocket.ChainListener.handle_info/2
    (stdlib 3.14.2.2) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.2.2) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:gproc_ps_event, :top_changed, %{info: %{block_hash: <<204, 91, 76, 107, 137, 20, 168, 191, 240, 182, 78, 225, 145, 20, 11, 255, 232, 219, 67, 224, 109, 157, 233, 71, 167, 222, 192, 106, 170, 27, 62, 32>>, block_type: :key, height: 126, prev_hash: <<107, 62, 234, 85, 153, 182, 16, 244, 41, 20, 97, 150, 233, 210, 179, 77, 205, 210, 116, 92, 74, 87, 247, 185, 229, 254, 111, 220, 78, 249, 232, 19>>}, sender: #PID<0.561.0>, time: {1704, 882415, 209055}}}
```

Starting with:
```
ubuntu@ip-10-0-4-26:~/aemdw$ docker run --name aemdw2 -d \
>     -u 1000:1000 \
>     -p 4000:4000 \
>     -v /data/aemdw/db1/mdw.db:/home/aeternity/node/local/rel/aeternity/data/mdw.db \
>     aeternity/ae_mdw:1.68.0
```

**Comment by yaboiishere** [comment]
I can't seem to reproduce this. When I connect with ws it works as expected
