### ISSUE TITLE
figure out root cause for name expiration inconsistencies

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#326]

**Comment by jyeshe** [comment]
```
iex(aeternity@localhost)4> :mnesia.sync_dirty(fn -> AeMdw.Db.Sync.Name.expire(397856) end)   
"blackberry.chain"
** (exit) an exception was raised:
    ** (RuntimeError) failed on :not_found
        (ae_mdw 1.2.1) lib/ae_mdw/util.ex:23: AeMdw.Util.ok!/1
        (ae_mdw 1.2.1) lib/ae_mdw/db/sync/name.ex:216: AeMdw.Db.Sync.Name.expire_auction/3
 ```

**Comment by jyeshe** [comment]
already active:
```
iex(aeternity@localhost)7> :mnesia.dirty_read(Model.ActiveName, "blackberry.chain")  
[
  {:name, "blackberry.chain", 397818, 447818,
   [{{397376, 3}, 20173626}, {{397371, 4}, 20173582}], [], [], nil, nil,
   <<28, 109, 234, 26, 22, 176, 95, 147, 251, 156, 73, 14, 255, 50, 231, 154,
     158, 230, 19, 69, 29, 173, 88, 20, 135, 251, 60, 185, 186, 100, 77, 213>>,
   nil}
]
iex(aeternity@localhost)8> owner = <<28, 109, 234, 26, 22, 176, 95, 147, 251, 156, 73, 14, 255, 50, 231, 154,                                                      
...(aeternity@localhost)8>      158, 230, 19, 69, 29, 173, 88, 20, 135, 251, 60, 185, 186, 100, 77, 213>>
iex(aeternity@localhost)9> :mnesia.dirty_read(Model.ActiveNameOwner, {owner,"blackberry.chain"})                                                                   
[
  {:owner,
   {<<28, 109, 234, 26, 22, 176, 95, 147, 251, 156, 73, 14, 255, 50, 231, 154,
      158, 230, 19, 69, 29, 173, 88, 20, 135, 251, 60, 185, 186, 100, 77, 213>>,
    "blackberry.chain"}, nil}
]
iex(aeternity@localhost)11> :mnesia.dirty_select(Model.ActiveNameExpiration, Ex2ms.fun do {:expiration, {height, "blackberry.chain"}, :_} -> height end)
[447818]
```

**Comment by jyeshe** [comment]
```
iex(aeternity@localhost)10> alias AeMdw.Db.{Model, Name}; require Model; Name.locate("homedepot.chain")                                   {{:name, "homedepot.chain", 408603, 633884,
  [{{408123, 13}, 20591612}, {{408121, 20}, 20591313}],
  [{{453884, 12}, 23747394}], [], nil, nil,
  <<71, 170, 205, 88, 171, 138, 158, 20, 128, 172, 247, 187, 201, 196, 64, 245,
    233, 129, 129, 121, 70, 250, 238, 155, 172, 111, 231, 169, 157, 32, 174,
    9>>, nil}, AeMdw.Db.Model.InactiveName}

iex(aeternity@localhost)9> :mnesia.dirty_select(Model.ActiveNameExpiration, Ex2ms.fun do {:expiration, {height, name}, :_} when name == "homedepot.chain" -> height end)
[633884]
iex(aeternity@localhost)10> :mnesia.dirty_select(Model.InactiveNameExpiration, Ex2ms.fun do {:expiration, {height, name}, :_} when name == "homedepot.chain" -> height end)
[458121]
```

**Comment by jyeshe** [comment]
Update tx with txi 23747394:
```
iex(aeternity@localhost)19> import AeMdw.Db.Util; [Model.tx(id: hash)] = read_tx 23747394; AeMdw.Node.Db.get_tx_data(hash)
{<<194, 189, 62, 228, 134, 180, 214, 93, 133, 35, 200, 72, 196, 107, 160, 68,
   157, 133, 31, 131, 189, 222, 132, 143, 14, 14, 137, 3, 69, 246, 79, 21>>,
 :name_update_tx,
 {:signed_tx,
  {:aetx, :name_update_tx, :aens_update_tx, 142,
   {:ns_update_tx,
    {:id, :account,
     <<71, 170, 205, 88, 171, 138, 158, 20, 128, 172, 247, 187, 201, 196, 64,
       245, 233, 129, 129, 121, 70, 250, 238, 155, 172, 111, 231, 169, 157, 32,
       174, 9>>}, 472,
    {:id, :name,
     <<36, 160, 188, 215, 76, 171, 90, 152, 85, 112, 60, 143, 52, 147, 23, 240,
       185, 26, 199, 22, 48, 179, 18, 25, 161, 227, 141, 251, 47, 123, 159,
       45>>}, 180000,
    [
      {:pointer, "account_pubkey",
       {:id, :account,
        <<71, 170, 205, 88, 171, 138, 158, 20, 128, 172, 247, 187, 201, 196, 64,
          245, 233, 129, 129, 121, 70, 250, 238, 155, 172, 111, 231, ...>>}}
    ], 84600, 17840000000000, 0}},
  [
    <<206, 107, 215, 119, 180, 107, 154, 101, 209, 239, 129, 211, 34, 63, 136,
      185, 153, 64, 244, 171, 10, 13, 144, 247, 42, 223, 14, 42, 235, 36, 10,
      24, 94, 156, 224, 152, 105, 179, 156, 242, 127, 204, 97, ...>>
  ]},
 {:ns_update_tx,
  {:id, :account,
   <<71, 170, 205, 88, 171, 138, 158, 20, 128, 172, 247, 187, 201, 196, 64, 245,
     233, 129, 129, 121, 70, 250, 238, 155, 172, 111, 231, 169, 157, 32, 174,
     9>>}, 472,
  {:id, :name,
   <<36, 160, 188, 215, 76, 171, 90, 152, 85, 112, 60, 143, 52, 147, 23, 240,
     185, 26, 199, 22, 48, 179, 18, 25, 161, 227, 141, 251, 47, 123, 159, 45>>},
  180000,
  [
    {:pointer, "account_pubkey",
     {:id, :account,
      <<71, 170, 205, 88, 171, 138, 158, 20, 128, 172, 247, 187, 201, 196, 64,
        245, 233, 129, 129, 121, 70, 250, 238, 155, 172, 111, 231, 169, 157, 32,
        174, 9>>}}
  ], 84600, 17840000000000, 0}}
```

**Comment by jyeshe** [comment]
```
iex(aeternity@localhost)67> {mod, tx} = :aetx.specialize_callback(:aetx_sign.tx(signed_tx)); tx_val(tx, :name_update_tx, :name_ttl)
180000
```

**Comment by jyeshe** [comment]
Name is inactivated on:
- update with delta_ttl == 0
- revoke
- expired

**Comment by jyeshe** [comment]
@thepiwo, considering what was explained and described above, this issue can be closed as not a bug from current Mdw source code standpoint of view.

**Comment by thepiwo** [comment]
thanks
