### ISSUE TITLE
call_not_found error on derive aex9 presence

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#364]
```
16:51:46.434 [error] Task #PID<0.4487.1> started from AeMdw.Sync.AsyncTasks.LongTaskConsumer terminating
** (RuntimeError) failed on {:error, :call_not_found}
    (ae_mdw 1.2.1) lib/ae_mdw/util.ex:23: AeMdw.Util.ok!/1
    (ae_mdw 1.2.1) lib/ae_mdw/contract.ex:286: AeMdw.Contract.call_tx_info/4
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:104: anonymous fn/4 in AeMdw.Sync.AsyncTasks.DeriveAex9Presence.read_aex9_transfers_from_mb/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:77: AeMdw.Sync.AsyncTasks.DeriveAex9Presence.get_aex9_recipients/3
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:44: AeMdw.Sync.AsyncTasks.DeriveAex9Presence.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:147: AeMdw.Sync.AsyncTasks.Consumer.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:111: anonymous fn/2 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by jyeshe** [comment]
After filtering correctly:
18:03:17.648 [error] Task #PID<0.5743.0> started from AeMdw.Sync.AsyncTasks.LongTaskConsumer terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in AeMdw.Sync.AsyncTasks.DeriveAex9Presence.get_aex9_recipients/3
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:78: anonymous fn([]) in AeMdw.Sync.AsyncTasks.DeriveAex9Presence.get_aex9_recipients/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/derive_aex9_presence.ex:44: AeMdw.Sync.AsyncTasks.DeriveAex9Presence.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:147: AeMdw.Sync.AsyncTasks.Consumer.process/1
    (ae_mdw 1.2.1) lib/ae_mdw/sync/async_tasks/consumer.ex:111: anonymous fn/2 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.33227004/0 in AeMdw.Sync.AsyncTasks.Consumer.run_supervised/2>
