### ISSUE TITLE
oracle integration test errors

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#541]
```
......

  1) test inactive_oracles get inactive oracles with default direction=backward and default limit (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:198
     match (=) failed
     code:  assert @default_limit = length(next_oracles)
     left:  @default_limit
     right: 8
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:217: (test)

....

  2) test oracle get oracle information for given oracle id with expand parameter (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:29
     ** (RuntimeError) expected response with status 200, got: 400, with body:
     "{\"error\":\"no such route\"}"
     code: assert conn |> json_response(200) |> Jason.encode!() ==
     stacktrace:
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:415: Phoenix.ConnTest.json_response/2
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:33: (test)

...

  3) test oracles get all oracles with default direction=backward and default limit (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:73
     match (=) failed
     code:  assert @default_limit = length(next_oracles)
     left:  @default_limit
     right: 2
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:91: (test)

.

  4) test oracle renders error when oracle id is invalid (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:42
     Assertion with == failed
     code:  assert json_response(conn, 400) == %{"error" => "invalid id: #{id}"}
     left:  %{"error" => "no such route"}
     right: %{"error" => "invalid id: invalid_oracle_id"}
     stacktrace:
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:46: (test)

..

  5) test oracle get oracle information for given oracle id (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:17
     ** (RuntimeError) expected response with status 200, got: 400, with body:
     "{\"error\":\"no such route\"}"
     code: assert json_response(conn, 200) ==
     stacktrace:
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:415: Phoenix.ConnTest.json_response/2
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:21: (test)

..

  6) test oracle it returns oracles registered through contract calls using Oracle.register (Integration.AeMdwWeb.OracleControllerTest)
     test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:49
     ** (RuntimeError) expected response with status 200, got: 404, with body:
     "{\"error\":\"not found: ok_zi3UaZkNWhxfR57tEE7ymNyQ2qHqtdZjQGQ7VpnmQ7MFdSL8A\"}"
     code: conn |> get("/oracle/#{oracle_id}") |> json_response(200)
     stacktrace:
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:369: Phoenix.ConnTest.response/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:415: Phoenix.ConnTest.json_response/2
       test/integration/ae_mdw_web/controllers/oracle_controller_test.exs:68: (test)



Finished in 8.1 seconds
24 tests, 6 failures
```

**Comment by jyeshe** [comment]
Not an issue
