### ISSUE TITLE
testnet contract not found on 1.7

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#586]
```
** (RuntimeError) Origin {:contract, <<115, 58, 92, 73, 111, 85, 214, 223, 85, 240, 254, 40, 105, 205, 139, 88, 161, 42, 130, 241, 100, 162, 118, 163, 59, 130, 156, 123, 249, 57, 234, 13>>} not found
    (ae_mdw 1.7.0) lib/ae_mdw/db/origin.ex:52: AeMdw.Db.Origin.tx_index!/1
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/contract.ex:150: AeMdw.Db.Sync.Contract.get_txi!/1
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:320: AeMdw.Db.Sync.Transaction.tx_mutations/1
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:144: AeMdw.Db.Sync.Transaction.transaction_mutations/3
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:243: anonymous fn/3 in AeMdw.Db.Sync.Transaction.micro_block_mutations/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:242: AeMdw.Db.Sync.Transaction.micro_block_mutations/2
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:189: anonymous fn/3 in AeMdw.Db.Sync.Transaction.do_sync_generation/2
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/transaction.ex:187: AeMdw.Db.Sync.Transaction.do_sync_generation/2
    (elixir 1.10.4) lib/enum.ex:3371: Enum.reduce_range_inc/4
    (ae_mdw 1.7.0) lib/ae_mdw/db/sync/sync.ex:99: AeMdw.Db.Sync.run_action/1
```

**Comment by thepiwo** [comment]
its the same issue as https://github.com/aeternity/ae_mdw/issues/536, right @sborrazas

**Comment by jyeshe** [comment]
#536 involves other contract but might have the same root cause.

**Comment by jyeshe** [comment]
Fully synced with 1.7.1
