### ISSUE TITLE
aex9 :not_present error on `balances_for_hash` gets balances for some hashes and each contract

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#653]
```
2) test balances_for_hash gets balances for some hashes and each contract (Integration.AeMdwWeb.Aex9ControllerTest)
     test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:290
     ** (ErlangError) Erlang error: {:not_present, <<0, 129, 48, 110, 159, 237, 166, 104, 33, 249, 249, 59, 27, 65, 28, 150, 25, 164, 14, 42, 153, 145, 35, 162, 246, 249, 43, 115, 228, 62, 90, 219>>}
     code: |> Enum.each(fn {contract_id, mb_hash} ->
     stacktrace:
       (aecontract 6.4.0) /home/rogerio/Workspace/ae/aeternity/apps/aecontract/src/aect_state_tree.erl:182: :aect_state_tree.get_contract/3
       (ae_mdw 1.7.2) lib/ae_mdw/dry_run/contract.ex:21: AeMdw.DryRun.Contract.new_call_tx/5
       (ae_mdw 1.7.2) lib/ae_mdw/contract.ex:236: AeMdw.Contract.call_contract/4
       (ae_mdw 1.7.2) lib/ae_mdw/node/db.ex:141: AeMdw.Node.Db.aex9_balances!/2
       (ae_mdw 1.7.2) lib/ae_mdw_web/controllers/aex9_controller.ex:357: AeMdwWeb.Aex9Controller.balances_for_hash_reply/3
       (ae_mdw 1.7.2) lib/ae_mdw_web/util.ex:82: AeMdwWeb.Util.handle_input/2
       (ae_mdw 1.7.2) lib/ae_mdw_web/controllers/aex9_controller.ex:1: AeMdwWeb.Aex9Controller.action/2
       (ae_mdw 1.7.2) lib/ae_mdw_web/controllers/aex9_controller.ex:1: AeMdwWeb.Aex9Controller.phoenix_controller_pipeline/2
       (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (ae_mdw 1.7.2) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.plug_builder_call/2
       (ae_mdw 1.7.2) lib/ae_mdw_web/endpoint.ex:1: AeMdwWeb.Endpoint.call/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:304: anonymous fn/2 in Integration.AeMdwWeb.Aex9ControllerTest."test balances_for_hash gets balances for some hashes and each contract"/1
       (elixir 1.10.4) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir 1.10.4) lib/enum.ex:783: Enum.each/2
       test/integration/ae_mdw_web/controllers/aex9_controller_test.exs:303: (test)
```

**Comment by jyeshe** [comment]
As part of new tests iterating throughout all existing aex9 contract pubkeys.

**Comment by jyeshe** [comment]
Not an issue: `ct_1DtebWK23btGPEnfiH3fxppd34S75uUryo5yGmb938Dx9Nyjt` did not exist yet at the tested hashes.
