### ISSUE TITLE
not syncing from height 0 using node database snapshot

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#763]
On a57cf3cc (master), in-memory/last mb sync error when syncing with empty mdw db and node snapshot (1.13):

```
2022-07-01 09:50:39.335 [error] Task #PID<0.3311.0> started from AeMdw.Sync.Server terminating
** (stop) {:aborted, {{:badmatch, []}, [{:aec_db, :"-get_block/1-fun-1-", 1, [file: '/home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl', line: 386]}, {:aec_db, :"-do_activity/2-fun-4-", 1, [file: '/home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl', line: 1346]}, {:mnesia_tm, :apply_fun, 3, [file: 'mnesia_tm.erl', line: 842]}, {:mnesia_tm, :execute_transaction, 5, [file: 'mnesia_tm.erl', line: 818]}, {:mnesia, :wrap_trans, 6, [file: 'mnesia.erl', line: 495]}, {:aec_db, :do_activity, 2, [file: '/home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl', line: 1345]}, {:aec_db, :try_activity, 4, [file: '/home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl', line: 1322]}, {AeMdw.Node.Db, :"-get_kb_mbs/1-fun-1-", 1, [file: 'lib/ae_mdw/node/db.ex', line: 60]}, {Stream, :do_unfold, 4, [file: 'lib/stream.ex', line: 1538]}, {Enum, :reduce_while, 3, [file: 'lib/enum.ex', line: 2161]}, {AeMdw.Node.Db, :"-get_blocks_per_height/3-fun-1-", 1, [file: 'lib/ae_mdw/node/db.ex', line: 43]}, {Stream, :do_unfold, 4, [file: 'lib/stream.ex', line: 1538]}, {Enum, :take_while, 2, [file: 'lib/enum.ex', line: 2960]}, {AeMdw.Node.Db, :get_blocks_per_height, 3, [file: 'lib/ae_mdw/node/db.ex', line: 51]}, {AeMdw.Db.Sync.Block, :blocks_mutations, 4, [file: 'lib/ae_mdw/db/sync/block.ex', line: 55]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {AeMdw.Sync.Server, :"-spawn_db_sync/3-fun-2-", 5, [file: 'lib/ae_mdw/sync/server.ex', line: 255]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 35]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
    (mnesia 4.16.3.1) mnesia.erl:497: :mnesia.wrap_trans/6
    (aecore 6.3.0) /home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl:1345: :aec_db.do_activity/2
    (aecore 6.3.0) /home/rogerio/Workspace/ae/aeternity/apps/aecore/src/aec_db.erl:1322: :aec_db.try_activity/4
    (ae_mdw 1.14.0) lib/ae_mdw/node/db.ex:60: anonymous fn/1 in AeMdw.Node.Db.get_kb_mbs/1
    (elixir 1.10.4) lib/stream.ex:1538: Stream.do_unfold/4
    (elixir 1.10.4) lib/enum.ex:2161: Enum.reduce_while/3
    (ae_mdw 1.14.0) lib/ae_mdw/node/db.ex:43: anonymous fn/1 in AeMdw.Node.Db.get_blocks_per_height/3
    (elixir 1.10.4) lib/stream.ex:1538: Stream.do_unfold/4
    (elixir 1.10.4) lib/enum.ex:2960: Enum.take_while/2
    (ae_mdw 1.14.0) lib/ae_mdw/node/db.ex:51: AeMdw.Node.Db.get_blocks_per_height/3
    (ae_mdw 1.14.0) lib/ae_mdw/db/sync/block.ex:55: AeMdw.Db.Sync.Block.blocks_mutations/4
    (stdlib 3.12.1.2) timer.erl:166: :timer.tc/1
    (ae_mdw 1.14.0) lib/ae_mdw/sync/server.ex:255: anonymous fn/5 in AeMdw.Sync.Server.spawn_db_sync/3
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<5.132972776/0 in AeMdw.Sync.Server.spawn_db_sync/3>
    Args: []
```

**Comment by sborrazas** [comment]
Fixed in #762
